name: Auto-Assign Reviewers

on:
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest

    steps:
    - name: Assign reviewers
      uses: kentaro-m/auto-assign-action@v1.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        reviewers: "oyoYnaY,team-member-1, team-member-2"
