name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '35 15 * * *'  # Runs daily at 15:35 UTC

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been automatically marked as stale because it has had no activity in the past 60 days. If no further activity occurs, it will be closed in 7 days.'
        stale-pr-message: 'This pull request has been marked as stale due to inactivity. If no updates are made, it will be closed in 7 days.'
        stale-issue-label: 'stale-issue'
        stale-pr-label: 'stale-pr'
        days-before-stale: 60  # Mark as stale after 60 days of inactivity
        days-before-close: 7   # Close the issue/PR 7 days after marking as stale
